### PR TITLE
Fix to support dialog bug on iOS

### PR DESCRIPTION
**Pull request by ziyafenn**
Fixed iOS bug with dialog appearing always on top. 

Also, removed `tabindex="1"` from the `exportButton` because on iOS it would automatically focus/scroll down to that button.

p.s. sorry for linter, it decided to prettify code again...

Only thing i change is how the modal being displayed.

#6

### CODE REVIEW

**Comment by edelstone** [comment]
I see a few issues with this @ziyafenn.

1. There are two conflicting files that need resolution (linter related?).
1. I'm noticing that when the page loads the "color copied to clipboard" message is present at the bottom, and all of the circled color swatches transition from square to circle. Maybe there is a new CSS rule specifying a transition for all?

Take a look and get back to me.

**Comment by edelstone** [comment]
Looking again, the second problem may predate these recent PRs. Seems new though.

**Comment by ziyafenn** [comment]
@edelstone yeah, two files changes, css file (i set `display:none` by default to the modal) and export.js to utilize than new css property.

About the second issue, i didn't touch any global variables. Only things related to modal, button and textarea. And i think I've noticed that behaviour previously as well.

**Comment by edelstone** [comment]
@ziyafenn Would you mind pulling the recent changes from `edelstone:master` and merge those with your branch so you can resolve the conflicts locally and then push again?

Below is what I see on my end. Pretty sure you kept working on your branch without pulling recent changes we already merged.

Screen Shot 2020-08-17 at 6 15 34 PM

**Comment by ziyafenn** [comment]
@edelstone sorry, forgot to first pull the changes from your master.

Can you please check if everything works. If yes, you can accept the PR.

**Pull request merged**
